#! /usr/bin/env python
#script creates a data file of density vs cycles

#import libraries needed
import readline
import numpy as np
import subprocess
import os
import time

if(os.path.isfile("./Isotherm")):
	Dirs = subprocess.Popen('ls -d */', stdout=subprocess.PIPE, cwd='./', shell=True)
	Pressures = Dirs.communicate()[0].replace("mbar/\n"," ").split()
	for p in Pressures:
		subprocess.Popen('grep -w -Ev "RestartFile|ContinueAfterCrash" simulation.input > t.dat', stdout=subprocess.PIPE, cwd='./'+ p + 'mbar/', shell=True)
		time.sleep(0.20)
		subprocess.Popen('sed "/WriteBinaryRestartFile/a ContinueAfterCrash    yes" t.dat > a.dat', stdout=subprocess.PIPE, cwd='./'+ p + 'mbar/', shell=True)
		time.sleep(0.20)
		subprocess.Popen('sed "/PrintEvery/a RestartFile    no" a.dat > b.dat', stdout=subprocess.PIPE, cwd='./'+ p + 'mbar/', shell=True)
		time.sleep(0.20)
		
		subprocess.Popen('rm simulation.input', stdout=subprocess.PIPE, cwd='./'+ p + 'mbar/', shell=True)
		subprocess.Popen('rm t.dat', stdout=subprocess.PIPE, cwd='./'+ p + 'mbar/', shell=True)
		subprocess.Popen('rm a.dat', stdout=subprocess.PIPE, cwd='./'+ p + 'mbar/', shell=True)
		subprocess.Popen('mv b.dat simulation.input', stdout=subprocess.PIPE, cwd='./'+ p + 'mbar/', shell=True)
		time.sleep(0.20)
		
		job = subprocess.Popen('sbatch job.slurm', stdout=subprocess.PIPE, cwd='./'+ p + 'mbar/', shell=True)
		print('{0} {1}'.format(job.communicate()[0].split()[3],str(p)+'mbar'))
else:
	print("\nERROR: You're not in the right directory")
	print("\nPlease navigate to a directory with the Isotherm flag")